public partial class Occurrence
{
    public string GbifID { get; set; }
    public string Abstract { get; set; }
    public string AccessRights { get; set; }
    public string AccrualMethod { get; set; }
    public string AccrualPeriodicity { get; set; }
    public string AccrualPolicy { get; set; }
    public string Alternative { get; set; }
    public string Audience { get; set; }
    public string Available { get; set; }
    public string BibliographicCitation { get; set; }
    public string ConformsTo { get; set; }
    public string Contributor { get; set; }
    public string Coverage { get; set; }
    public string Created { get; set; }
    public string Creator { get; set; }
    public string Date { get; set; }
    public string DateAccepted { get; set; }
    public string DateCopyrighted { get; set; }
    public string DateSubmitted { get; set; }
    public string Description { get; set; }
    public string EducationLevel { get; set; }
    public string Extent { get; set; }
    public string Format { get; set; }
    public string HasFormat { get; set; }
    public string HasPart { get; set; }
    public string HasVersion { get; set; }
    public string Identifier { get; set; }
    public string InstructionalMethod { get; set; }
    public string IsFormatOf { get; set; }
    public string IsPartOf { get; set; }
    public string IsReferencedBy { get; set; }
    public string IsReplacedBy { get; set; }
    public string IsRequiredBy { get; set; }
    public string IsVersionOf { get; set; }
    public string Issued { get; set; }
    public string Language { get; set; }
    public string License { get; set; }
    public string Mediator { get; set; }
    public string Medium { get; set; }
    public string Modified { get; set; }
    public string Provenance { get; set; }
    public string Publisher { get; set; }
    public string References { get; set; }
    public string Relation { get; set; }
    public string Replaces { get; set; }
    public string Requires { get; set; }
    public string Rights { get; set; }
    public string RightsHolder { get; set; }
    public string Source { get; set; }
    public string Spatial { get; set; }
    public string Subject { get; set; }
    public string TableOfContents { get; set; }
    public string Temporal { get; set; }
    public string Title { get; set; }
    public string Type { get; set; }
    public string Valid { get; set; }
    public string InstitutionID { get; set; }
    public string CollectionID { get; set; }
    public string DatasetID { get; set; }
    public string InstitutionCode { get; set; }
    public string CollectionCode { get; set; }
    public string DatasetName { get; set; }
    public string OwnerInstitutionCode { get; set; }
    public string BasisOfRecord { get; set; }
    public string InformationWithheld { get; set; }
    public string DataGeneralizations { get; set; }
    public string DynamicProperties { get; set; }
    public string OccurrenceID { get; set; }
    public string CatalogNumber { get; set; }
    public string RecordNumber { get; set; }
    public string RecordedBy { get; set; }
    public int? IndividualCount { get; set; }
    public string OrganismQuantity { get; set; }
    public string OrganismQuantityType { get; set; }
    public string Sex { get; set; }
    public string LifeStage { get; set; }
    public string ReproductiveCondition { get; set; }
    public string Behavior { get; set; }
    public string EstablishmentMeans { get; set; }
    public string OccurrenceStatus { get; set; }
    public string Preparations { get; set; }
    public string Disposition { get; set; }
    public string AssociatedReferences { get; set; }
    public string AssociatedSequences { get; set; }
    public string AssociatedTaxa { get; set; }
    public string OtherCatalogNumbers { get; set; }
    public string OccurrenceRemarks { get; set; }
    public string OrganismID { get; set; }
    public string OrganismName { get; set; }
    public string OrganismScope { get; set; }
    public string AssociatedOccurrences { get; set; }
    public string AssociatedOrganisms { get; set; }
    public string PreviousIdentifications { get; set; }
    public string OrganismRemarks { get; set; }
    public string MaterialSampleID { get; set; }
    public string EventID { get; set; }
    public string ParentEventID { get; set; }
    public string FieldNumber { get; set; }
    public string EventDate { get; set; }
    public string EventTime { get; set; }
    public int? StartDayOfYear { get; set; }
    public int? EndDayOfYear { get; set; }
    public int? Year { get; set; }
    public int? Month { get; set; }
    public int? Day { get; set; }
    public string VerbatimEventDate { get; set; }
    public string Habitat { get; set; }
    public string SamplingProtocol { get; set; }
    public string SamplingEffort { get; set; }
    public int? SampleSizeValue { get; set; }
    public string SampleSizeUnit { get; set; }
    public string FieldNotes { get; set; }
    public string EventRemarks { get; set; }
    public string LocationID { get; set; }
    public string HigherGeographyID { get; set; }
    public string HigherGeography { get; set; }
    public string Continent { get; set; }
    public string WaterBody { get; set; }
    public string IslandGroup { get; set; }
    public string Island { get; set; }
    public string CountryCode { get; set; }
    public string StateProvince { get; set; }
    public string County { get; set; }
    public string Municipality { get; set; }
    public string Locality { get; set; }
    public string VerbatimLocality { get; set; }
    public string VerbatimElevation { get; set; }
    public string VerbatimDepth { get; set; }
    public double? MinimumDistanceAboveSurfaceInMeters { get; set; }
    public double? MaximumDistanceAboveSurfaceInMeters { get; set; }
    public string LocationAccordingTo { get; set; }
    public string LocationRemarks { get; set; }
    public double? DecimalLatitude { get; set; }
    public double? DecimalLongitude { get; set; }
    public double? CoordinateUncertaintyInMeters { get; set; }
    public double? CoordinatePrecision { get; set; }
    public double? PointRadiusSpatialFit { get; set; }
    public string VerbatimCoordinateSystem { get; set; }
    public string VerbatimSRS { get; set; }
    public string FootprintWKT { get; set; }
    public string FootprintSRS { get; set; }
    public double? FootprintSpatialFit { get; set; }
    public string GeoreferencedBy { get; set; }
    public string GeoreferencedDate { get; set; }
    public string GeoreferenceProtocol { get; set; }
    public string GeoreferenceSources { get; set; }
    public string GeoreferenceVerificationStatus { get; set; }
    public string GeoreferenceRemarks { get; set; }
    public string GeologicalContextID { get; set; }
    public string EarliestEonOrLowestEonothem { get; set; }
    public string LatestEonOrHighestEonothem { get; set; }
    public string EarliestEraOrLowestErathem { get; set; }
    public string LatestEraOrHighestErathem { get; set; }
    public string EarliestPeriodOrLowestSystem { get; set; }
    public string LatestPeriodOrHighestSystem { get; set; }
    public string EarliestEpochOrLowestSeries { get; set; }
    public string LatestEpochOrHighestSeries { get; set; }
    public string EarliestAgeOrLowestStage { get; set; }
    public string LatestAgeOrHighestStage { get; set; }
    public string LowestBiostratigraphicZone { get; set; }
    public string HighestBiostratigraphicZone { get; set; }
    public string LithostratigraphicTerms { get; set; }
    public string Group { get; set; }
    public string Formation { get; set; }
    public string Member { get; set; }
    public string Bed { get; set; }
    public string IdentificationID { get; set; }
    public string IdentificationQualifier { get; set; }
    public string TypeStatus { get; set; }
    public string IdentifiedBy { get; set; }
    public DateTime? DateIdentified { get; set; }
    public string IdentificationReferences { get; set; }
    public string IdentificationVerificationStatus { get; set; }
    public string IdentificationRemarks { get; set; }
    public string TaxonID { get; set; }
    public string ScientificNameID { get; set; }
    public string AcceptedNameUsageID { get; set; }
    public string ParentNameUsageID { get; set; }
    public string OriginalNameUsageID { get; set; }
    public string NameAccordingToID { get; set; }
    public string NamePublishedInID { get; set; }
    public string TaxonConceptID { get; set; }
    public string ScientificName { get; set; }
    public string AcceptedNameUsage { get; set; }
    public string ParentNameUsage { get; set; }
    public string OriginalNameUsage { get; set; }
    public string NameAccordingTo { get; set; }
    public string NamePublishedIn { get; set; }
    public int? NamePublishedInYear { get; set; }
    public string HigherClassification { get; set; }
    public string Kingdom { get; set; }
    public string Phylum { get; set; }
    public string Class { get; set; }
    public string Order { get; set; }
    public string Family { get; set; }
    public string Genus { get; set; }
    public string Subgenus { get; set; }
    public string SpecificEpithet { get; set; }
    public string InfraspecificEpithet { get; set; }
    public string TaxonRank { get; set; }
    public string VerbatimTaxonRank { get; set; }
    public string VernacularName { get; set; }
    public string NomenclaturalCode { get; set; }
    public string TaxonomicStatus { get; set; }
    public string NomenclaturalStatus { get; set; }
    public string TaxonRemarks { get; set; }
    public string DatasetKey { get; set; }
    public string PublishingCountry { get; set; }
    public string LastInterpreted { get; set; }
    public string Elevation { get; set; }
    public string ElevationAccuracy { get; set; }
    public string Depth { get; set; }
    public string DepthAccuracy { get; set; }
    public string DistanceAboveSurface { get; set; }
    public string DistanceAboveSurfaceAccuracy { get; set; }
    public string Issue { get; set; }
    public string MediaType { get; set; }
    public string HasCoordinate { get; set; }
    public string HasGeospatialIssues { get; set; }
    public string TaxonKey { get; set; }
    public string AcceptedTaxonKey { get; set; }
    public string KingdomKey { get; set; }
    public string PhylumKey { get; set; }
    public string ClassKey { get; set; }
    public string OrderKey { get; set; }
    public string FamilyKey { get; set; }
    public string GenusKey { get; set; }
    public string SubgenusKey { get; set; }
    public string SpeciesKey { get; set; }
    public string Species { get; set; }
    public string GenericName { get; set; }
    public string AcceptedScientificName { get; set; }
    public string VerbatimScientificName { get; set; }
    public string TypifiedName { get; set; }
    public string Protocol { get; set; }
    public string LastParsed { get; set; }
    public string LastCrawled { get; set; }
    public string Repatriated { get; set; }
    public string RelativeOrganismQuantity { get; set; }
    public string RecordedByID { get; set; }
    public string IdentifiedByID { get; set; }
    public string Level0Gid { get; set; }
    public string Level0Name { get; set; }
    public string Level1Gid { get; set; }
    public string Level1Name { get; set; }
    public string Level2Gid { get; set; }
    public string Level2Name { get; set; }
    public string Level3Gid { get; set; }
    public string Level3Name { get; set; }
    public string IucnRedListCategory { get; set; }
}