# This is a basic workflow to help you get started with Actions
name: PublishNuget

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/DwC-A_dotnet.Interactive/DwC-A_dotnet.Interactive.csproj 
          # NuGet package id, used for version detection & defaults to project name
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
